### ISSUE TITLE
gpu使用率过低

### ISSUE THREAD

**Issue by huwenkai26** [alibaba-damo-academy/FunASR#1018]
``OS: Ubuntu
Python
funasr                         0.7.8
modelscope                     1.9.1
torchaudio                     2.0.2
Model: damo/speech_paraformer-large-vad-punc-spk_asr_nat-zh-cn
`from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

if __name__ == '__main__':
    audio_in = 'https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/test_audio/asr_speaker_demo.wav'
    output_dir = "./results"
    inference_pipeline = pipeline(
        task=Tasks.auto_speech_recognition,
        model='damo/speech_paraformer-large-vad-punc-spk_asr_nat-zh-cn',
        model_revision='v0.0.2',
        vad_model='damo/speech_fsmn_vad_zh-cn-16k-common-pytorch',
        punc_model='damo/punc_ct-transformer_cn-en-common-vocab471067-large',
        output_dir=output_dir,
    )
    rec_result = inference_pipeline(audio_in=audio_in, batch_size_token=5000, batch_size_token_threshold_s=40, max_single_segment_time=6000)
    print(rec_result)
`
![image](https://github.com/alibaba-damo-academy/FunASR/assets/17784674/ac994053-3a6f-42fc-bb42-f05fd85274c2)

**Comment by LauraGPT** [comment]
1. You should update funasr-0.8.0, [docs](https://alibaba-damo-academy.github.io/FunASR/en/installation/installation.html).
2. The pipeline use multiple models, such as, asr, vad, punc, sd. When performing batch computations for the ASR model, the GPU can be efficiently utilized for high efficiency. However, for other models like VAD, the GPU utilization is low due to their low computation requirements.
